version: '3.9'
services:
  web:
    build: .
    depends_on:
      - db
    networks:
      - traefik-public
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.badge42.entrypoints: https
      traefik.http.routers.badge42.rule: Host(`badge.emaugale.com`)
      traefik.http.routers.badge42.tls: true
      traefik.http.routers.badge42.tls.certresolver: myresolver
      traefik.http.services.badge42.loadbalancer.server.port: 3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - FORTY_TWO_CLIENT_ID=${FORTY_TWO_CLIENT_ID}
      - FORTY_TWO_CLIENT_SECRET=${FORTY_TWO_CLIENT_SECRET}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
  db:
    image: postgres
    restart: unless-stopped
    networks:
      - traefik-public
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: "YOUR_USER"
      POSTGRES_PASSWORD: "YOUR_PASSWD"
      POSTGRES_DB: "badge42"

volumes:
  db:

networks:
  traefik-public:
    external: true
