version: '3.9'
services:
  web:
    build: .
    depends_on:
      - db
    networks:
      - traefik_traefik
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.badge42.entrypoints: https
      traefik.http.routers.badge42.rule: Host(`badge.emaugale.com`)
      traefik.http.routers.badge42.tls: true
      traefik.http.routers.badge42.tls.certresolver: letsencrypt
      traefik.http.services.badge42.loadbalancer.server.port: 3000
    environment:
      DATABASE_URL: "postgres://YOUR_USER:YOUR_PASSWD@db:5432/badge42"
      NEXTAUTH_URL: "https://badge.emaugale.com"
      NEXTAUTH_SECRET: YOUR_RANDOM_SECRET
      FORTY_TWO_CLIENT_ID: YOUR_42API_CLIENT
      FORTY_TWO_CLIENT_SECRET: YOUR_42API_SECRET
      GITHUB_ID: "YOUR_GITHUB_APP_ID"
      GITHUB_SECRET: "YOUR_GITHUB_APP_SECRET"

  db:
    image: postgres
    restart: unless-stopped
    networks:
      - traefik_traefik
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: "YOUR_USER"
      POSTGRES_PASSWORD: "YOUR_PASSWD"
      POSTGRES_DB: "badge42"

volumes:
  db:

networks:
  traefik_traefik:
    external: true
